<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="header">
        <div class="logo-wrap">
            <img src="image/trident.jpg" alt="Diia" class="logo">
        </div>
        <div class="platform-name">Платформа<br>реєстрів</div>
    </div>
    <div class="main">
        Код підтвердження: ${verificationCode}
    </div>
    <div class="footer">
        Адреса чи службова інформація
    </div>
</body>
</html>
